
CREATE DATABASE INSTAGRAM_CLIENTS
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER 'client'@'localhost' IDENTIFIED BY 'q1';
GRANT SELECT, UPDATE ON INSTAGRAM_CLIENTS.CLIENTS TO 'client'@'localhost';
GRANT INSERT, SELECT, UPDATE ON INSTAGRAM_CLIENTS.SESSIONS TO 'client'@'localhost';
GRANT SELECT ON INSTAGRAM_CLIENTS.ANNOUNCEMENT TO 'client'@'localhost';
FLUSH PRIVILEGES;

SET SQL_MODE='ALLOW_INVALID_DATES';

USE INSTAGRAM_CLIENTS;

CREATE TABLE CLIENTS
(
  CLIENT_ID VARCHAR(36),
  CLIENT_NAME VARCHAR(50) NULL,
  VALID_THROUGH TIMESTAMP NULL DEFAULT NULL,
  IS_LOGGED_IN_NOW BOOLEAN,
  CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  COMMENT VARCHAR(100) NULL,
  ENABLED BOOLEAN,

  PRIMARY KEY (CLIENT_ID)
);


CREATE TABLE SESSIONS
(
  SESSION_ID INT AUTO_INCREMENT,
  CLIENT_ID VARCHAR(36),
  IPs VARCHAR(255),
  START_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  END_TIME TIMESTAMP NULL DEFAULT NULL,

  PRIMARY KEY (SESSION_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);


CREATE TABLE ANNOUNCEMENT
(
  ANNOUNCEMENT VARCHAR(1024) DEFAULT NULL
);
INSERT INTO ANNOUNCEMENT VALUES (NULL);

# TEST   UUID()
INSERT INTO CLIENTS (CLIENT_ID, CLIENT_NAME, VALID_THROUGH, IS_LOGGED_IN_NOW, ENABLED)
VALUES ('TEST-UUID-123908', 'TEST1', DATE_ADD(NOW(), INTERVAL +1 MONTH), FALSE, TRUE);
