
CREATE DATABASE TEST_INSTAGRAM_CLIENTS
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER 'tester'@'localhost' IDENTIFIED BY 'q1';
GRANT INSERT, SELECT, UPDATE, DELETE ON TEST_INSTAGRAM_CLIENTS.CLIENTS TO 'tester'@'localhost';
GRANT INSERT, SELECT, UPDATE, DELETE ON TEST_INSTAGRAM_CLIENTS.SESSIONS TO 'tester'@'localhost';
GRANT INSERT, SELECT, UPDATE, DELETE ON TEST_INSTAGRAM_CLIENTS.ANNOUNCEMENT TO 'tester'@'localhost';
FLUSH PRIVILEGES;

SET SQL_MODE='ALLOW_INVALID_DATES';

USE TEST_INSTAGRAM_CLIENTS;

CREATE TABLE CLIENTS
(
  CLIENT_ID VARCHAR(36),
  CLIENT_NAME VARCHAR(50) NULL,
  VALID_THROUGH TIMESTAMP NULL DEFAULT NULL,
  IS_LOGGED_IN_NOW BOOLEAN,
  CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  COMMENT VARCHAR(100) NULL,
  ENABLED BOOLEAN,

  PRIMARY KEY (CLIENT_ID)
);


CREATE TABLE SESSIONS
(
  SESSION_ID INT AUTO_INCREMENT,
  CLIENT_ID VARCHAR(36),
  IPs VARCHAR(255),
  START_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  END_TIME TIMESTAMP NULL DEFAULT NULL,

  PRIMARY KEY (SESSION_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);


CREATE TABLE ANNOUNCEMENT
(
  ANNOUNCEMENT VARCHAR(1024) DEFAULT NULL
);
